project:
  type: website
  output-dir: docs

format:
  html:
    theme: cosmo
    css: styles.css

website:
  title: "Aprendiendo R"
  navbar:
    left:
      - href: index.html
        text: Intro-R
      - href: 3_Zotero.html
        text: Zotero
      - href: 5_Sample.html
        text: Muestreo