project:
  type: website

website:
  title: "Aprendiendo R"
  navbar:
    left:
      - href: 1_Basico.html
        text: Intro-R
      - href: 3_Zotero.html
        text: Zotero
      - href: 5_Sample.html
        text: Muestreo